### PR TITLE
Add Macro Engineering Fellowship to course list

### PR DESCRIPTION
**Pull request by joaostein**
There was no documentation on a process to follow regarding PRs, so I made it simple & clean.

If there's anything to adjust, please let me know 😉.

### CODE REVIEW

**Comment by joaostein** [comment]
@wslyvh updated the description language so it's cleaner

**Comment by wslyvh** [comment]
Hi, thanks for submitting the fellowship here. It seems like there's a tuition fee (of 1 ETH) for it?

While I understand quality content can be worth it, the focus on useWeb3 is free and accessible content.
If you have any free, entry-level or other accessible content feel free to re-submit.

**Comment by joaostein** [comment]
@wslyvh do you have any plans on opening a spot to promote the [Macro Engineering Fellowship](https://0xmacro.com/engineering-fellowship)? I noticed that we have [[1](https://www.useweb3.xyz/courses/chainshot)] and [[2](https://www.useweb3.xyz/courses/consensys-academy)] which are paid courses listed in the `/courses` page and wondering if we can add our Fellowship in there. In the case we want to stick with the "free only" policy, can we discuss opening a new section on the website to move [1] and [2], add our Fellowship, and flag all the paid web3-focused courses separately?

**Comment by wslyvh** [comment]
Both Chainshot and ConsenSys offer free courses. 

I'll consider a 'paid courses' section, but don't expect to anything on short notice. I believe there are enough free educational resources for people to get started. If they want to know more, they usually can find their way around in the ecosystem enough to make their own decisions

**Pull request closed without merging**
