### PR TITLE
Create -cyfrin-updraft.md

### PR DESCRIPTION
**Pull request by Eversmile12**
Adds Cyfrin Updraft [updraft.cyfrin.io](updraft.cyfrin.io) to the courses. 

Cyfrin Updraft is a learning platform containing the old and new Patrick Collins' courses, re-organised for a 10x better learning experience. Completely free, currently on early access.

### CODE REVIEW

**Comment by wslyvh** [comment]
Hi Vitto, super excited with what you guys are building! 
Any ETA when early access gets lifted and this goes public? I'd love to feature this, but try to focus on content that is publicly available

**Comment by Eversmile12** [comment]
Hey Wslyvh! 

Thank you so much, did you get your early access?

So, we still need some time to make everything open - but starting next week two courses will already be made public:
- Blockchain Basics
- Solidity 101

Would that work?

**Comment by wslyvh** [comment]
I did not. Would love to check out it, but currently won't have much bandwidth to dive in too much, unfortunately! 

Let me know when those first courses go public. Would love to add it then. Hope that's ok!

**Comment by Eversmile12** [comment]
Hey @wslyvh! 

After our conversation - We made the security course open https://updraft.cyfrin.io/courses/security

The plan is to progressively open everything in the next few months. Let me know if this works!

Thank you so much
Vitto

**Comment by wslyvh** [comment]
Nice! Great to see. Merged :)

**Comment by Eversmile12** [comment]
Thank you ser! 

Tried searching for it but didn't find Updraft on the website - any idea why?

**Comment by wslyvh** [comment]
Had a build error. Should be updated now.
Also bumped it up to be a featured under courses, so you can check on the homepage already

**Comment by Eversmile12** [comment]
Thank you ser! Appreciated 🙏🏼

**Pull request merged**
