### PR TITLE
Create cryptoneur-grant-database

### PR DESCRIPTION
**Pull request by feliche93**
Adds new grant resource.

### CODE REVIEW

**Comment by wslyvh** [comment]
This is similar to our own grants page
https://www.useweb3.xyz/grants

**Comment by feliche93** [comment]
@wslyvh yep I know, I just built something that was supposed to compliment your offering, but I guess you don't find it useful?

**Comment by wslyvh** [comment]
I don't think it's add much value compared to what's already here, no.

I'd rather see submissions for other grant programs / or functionalities that improve the experience on useWeb3.

**Comment by feliche93** [comment]
Ok, happy to link back to yours as I believe helping ppl to find grants is not zero sum. Thanks for the quick feedback though!

**Pull request closed without merging**
