### PR TITLE
feat: add a toggleable side nav for mobile

### PR DESCRIPTION
**Pull request by G3root**
## context for this PR.

currently mobile devices has small reading space due to persistent sidenav, this PR fixes that.

### CODE REVIEW

**Comment by wslyvh** [comment]
This is great! 

I'd like to suggest a change tho. 
In the previous scenario there are basically 2 major breakpoints.
1 for large screens, which shows the full menu: icon + text 
Anything below large screens, show the collapsed menu with just the icon

This new version goes from the full menu (icon + text) to the hidden/FAB style.
I'd like to see the collapsed menu, with just the icons, for screen sizes in between. 

So.
Large screens/desktop: full menu
Medium-small screens: collapsed menu
Mobile / small screens: FAB

**Comment by G3root** [comment]
> This is great! 
> 
> I'd like to suggest a change tho. 
> In the previous scenario there are basically 2 major breakpoints.
> 1 for large screens, which shows the full menu: icon + text 
> Anything below large screens, show the collapsed menu with just the icon
> 
> This new version goes from the full menu (icon + text) to the hidden/FAB style.
> I'd like to see the collapsed menu, with just the icons, for screen sizes in between. 
> 
> So.
> Large screens/desktop: full menu
> Medium-small screens: collapsed menu
> Mobile / small screens: FAB 
> 

That's great I'll send a PR today.

**Comment by wslyvh** [comment]
The build currently fails from the es5 target change at #10 
So I can't see deploy a preview atm.

**Comment by G3root** [comment]
> The build currently fails from the es5 target change at #10 
> So I can't see deploy a preview atm. 
I can't figure out why I changed that , I'll send a PR for that

**Comment by G3root** [comment]
> The build currently fails from the es5 target change at #10 
> So I can't see deploy a preview atm. 

I can't figure out why I changed that 😅 , I'll send a PR

**Comment by wslyvh** [comment]
Merged! Thanks for your patience and the fixes :)

**Pull request merged**
