### PR TITLE
Added multiple themes to site

### PR DESCRIPTION
**Pull request by helloitsm3**
Themes include
- Light
- Dark
- Blueberry Dark
- Pantone

### CODE REVIEW

**Comment by wslyvh** [comment]
Thank you for re-submitting. This is so much easier to review. And it looks great :)
Preview url at https://useweb3-dxro3ltkl-useweb3.vercel.app/ 

There are still edge cases with different breakpoints though.
<1280 screen size - hides the menu text, but due to the dropdown theme selector at the bottom is too wide 
image

<640 screen size - the entire menu is hidden and replaced by a FAB. The theme selector isn't available anymore. It actually seems like it's a completely different menu/component as it also doesn't take over the selected theme/colors

**Comment by helloitsm3** [comment]
I'll take a look at it. I noticed that there are some inconsistencies with the quotes being used in certain files too. Was this intentional? I've tried enabling "Format on Save" in VScode with the use of your prettier config but it's causing a lot of styling issues as mentioned previously. Is there anyway we can standardise this?

**Comment by wslyvh** [comment]
Nice! Almost there... I just found 1 more component that doesn't correctly update colors yet..
image

> I'll take a look at it. I noticed that there are some inconsistencies with the quotes being used in certain files too. Was this intentional? I've tried enabling "Format on Save" in VScode with the use of your prettier config but it's causing a lot of styling issues as mentioned previously. Is there anyway we can standardise this?

Not intentional no. I'm not that familiar with setting up prettier properly as I don't use it.
(obviously, since all the inconsistencies :))
I only added .ts/.tsx files in the prettier command tho (package.json). I can imagine you're more into .scss at the moment?

I'll have another look at it.. Or open to PRs. 
But let's make it a separate one then. This one is almost ready

**Comment by wslyvh** [comment]
I tried to update and push directly to your PR, but I didn't have permissions for that.

It's a small change, you can see it here
https://github.com/wslyvh/useWeb3/commit/f10ea2ad1a0d36478722497c7d14c33feaf93e44

**Comment by helloitsm3** [comment]
> Nice! Almost there... I just found 1 more component that doesn't correctly update colors yet.. image
> 
> > I'll take a look at it. I noticed that there are some inconsistencies with the quotes being used in certain files too. Was this intentional? I've tried enabling "Format on Save" in VScode with the use of your prettier config but it's causing a lot of styling issues as mentioned previously. Is there anyway we can standardise this?
> 
> Not intentional no. I'm not that familiar with setting up prettier properly as I don't use it. (obviously, since all the inconsistencies :)) I only added .ts/.tsx files in the prettier command tho (package.json). I can imagine you're more into .scss at the moment?
> 
> I'll have another look at it.. Or open to PRs. But let's make it a separate one then. This one is almost ready

Yup, we can work on the prettier config together once this PR is merged. I use prettier a lot to auto format my code since it's very convenient

**Pull request merged**
